# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-25 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTab',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=128)),
                ('author', models.CharField(default='', max_length=128)),
                ('create_time', models.PositiveIntegerField(default=1218154088)),
                ('update_time', models.PositiveIntegerField(default=1218154088)),
                ('body', models.TextField(default='')),
            ],
            options={
                'db_table': 'article_tab',
            },
        ),
    ]
